/* Meter-report totals and hourly estimates stay separate; this file only presents them. */
lang=localStorage.getItem('sta-language')||'th';
const previousRender=render;
const palette={solar:'#53f6ce',load:'#d994ff',grid:'#ffc76b',export:'#ff8495'};
let chartSequence=0,chartData=new Map();
const mainSections=[0,1,3,4,5];
const sectionLabels=[['Overview','ภาพรวม'],['Energy & daily trends','พลังงานและรายวัน'],['Inverters','อินเวอร์เตอร์'],['Insights & checks','วิเคราะห์และตรวจสอบ'],['Data & updates','ข้อมูลและอัปเดต']];
function metricCard(label,value,unit,color=palette.load,detail=''){
 return `<article class="card" style="--accent:${color}"><small>${escape(label)}</small><b style="color:${color}">${value}</b><span>${escape(unit)}</span>${detail?`<p>${escape(detail)}</p>`:''}</article>`;
}
function energyCards(row,unit='MWh'){
 const scale=unit==='MWh'?1000:1;
 return `<div class="cards">${[[t('Solar generation','โซลาร์ผลิต'),row['Inverters Produced_kWh'],palette.solar],[t('Factory consumption','โรงงานใช้ไฟ'),row['Consumed Energy_kWh'],palette.load],[t('Grid import','ซื้อไฟจากการไฟฟ้า'),row['Imported Energy_kWh'],palette.grid],[t('Grid export','ส่งออกเข้าการไฟฟ้า'),row['Exported Energy_kWh'],palette.export]].map(x=>metricCard(x[0],n(x[1]/scale,2),unit,x[2])).join('')}</div>`;
}
function energyRing(percent,color,label){const v=Math.max(0,Math.min(100,Number(percent)||0));return `<div class="donut"><svg viewBox="0 0 120 120" role="img" aria-label="${escape(label)} ${n(v,2)}%"><circle cx="60" cy="60" r="48" fill="none" stroke="#243c4c" stroke-width="10"/><circle cx="60" cy="60" r="48" fill="none" stroke="${color}" stroke-width="10" stroke-linecap="round" pathLength="100" stroke-dasharray="${v} 100" transform="rotate(-90 60 60)"/></svg><div class="donut-value"><b>${n(v,2)}%</b><small>${escape(label)}</small></div></div>`}
function balancePanel(){let s=D.summary;return `<section class="panel"><h2>${t('Energy use at a glance','สัดส่วนพลังงานที่ใช้')}</h2><div class="balance-grid"><div class="balance-card">${energyRing(s.self_consumption_pct,palette.solar,t('Self-consumed','ใช้โซลาร์เอง'))}<div><h3>${t('Solar stays in the factory','โซลาร์ส่วนใหญ่ใช้ในโรงงาน')}</h3><p><strong>${n(s.self_consumed_solar_kWh/1000,2)} MWh</strong> ${t('used on site','ใช้ภายในโรงงาน')}</p><p class="muted">${t('Exported','ส่งออก')} ${n(s['Exported Energy_kWh'],3)} kWh</p></div></div><div class="balance-card">${energyRing(s.solar_share_pct,palette.load,t('Solar share','โซลาร์ต่อโหลด'))}<div><h3>${t('How much solar covers','โซลาร์ช่วยจ่ายโหลดโรงงาน')}</h3><p><strong>${n(s.solar_share_pct,2)}%</strong> ${t('of total consumption','ของไฟฟ้าที่โรงงานใช้')}</p><p class="muted">${t('Grid import','ซื้อไฟจากการไฟฟ้า')} ${n(s['Imported Energy_kWh']/1000,2)} MWh</p></div></div></div></section>`}
function flowIcon(kind){const paths={solar:'M3 9h18l-2 10H5L3 9Z M7 9l1 10 M12 9v10 M17 9l-1 10 M4 14h16 M9 22h6 M12 19v3 M12 2v3 M4 3l2 3 M20 3l-2 3',factory:'M3 21V9l6 4V9l6 4V3h4v18H3Z M7 17h2 M12 17h2 M17 17h2',grid:'M12 2L5 22 M12 2l7 20 M8 15h8 M9 10h6 M7 20h10 M5 6h14 M3 10h18'};return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[kind]}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function overviewHero(){return `<section class="volta-hero"><div><span class="eyebrow">PEA · SOLAREDGE · SRI TRANG</span><h2>STA PL 3MW</h2><p>${t('Sri Trang Solar Farm · Energy monitoring','Solar Farm ศรีตรัง · ติดตามพลังงาน')}</p><span class="hero-period">${t('September 2026 · Historical report','กันยายน 2569 · รายงานย้อนหลัง')}</span></div><div class="site-summary"><div><small>${t('Installed DC capacity','กำลังติดตั้ง DC')}</small><strong>2,526.48 <em>kWp</em></strong></div><div><small>${t('Inverter fleet','อินเวอร์เตอร์ทั้งหมด')}</small><strong>24 <em>${t('units','เครื่อง')}</em></strong></div><span>${t('STA-PHS · TR 3000 kVA','STA-PHS · TR 3000 kVA')}</span></div></section>`}
function chartLabel(key){return ({'Inverters Produced_kWh':t('Solar generation','โซลาร์ผลิต'),'Consumed Energy_kWh':t('Factory consumption','โรงงานใช้ไฟ'),'Imported Energy_kWh':t('Grid import','ซื้อไฟจากการไฟฟ้า'),'Production_mean_kW':t('Solar power','กำลังโซลาร์'),'Consumption_mean_kW':t('Factory load','โหลดโรงงาน'),'From Grid_mean_kW':t('Grid power','กำลังจากการไฟฟ้า'),'To Building_mean_kW':t('Solar → Factory','โซลาร์ → โรงงาน'),'To Grid_mean_kW':t('Solar → Grid','โซลาร์ → ส่งออก'),'From Solar_mean_kW':t('Consumption from solar','ใช้ไฟจากโซลาร์'),'From Grid_mean_kW':t('Consumption from grid','ใช้ไฟจากการไฟฟ้า'),'energy_kWh':t('Inverter production','พลังงานอินเวอร์เตอร์'),'irradiance_DIRECT_source_units':t('DIRECT light sensor (source units)','เซ็นเซอร์แสง DIRECT (หน่วยต้นฉบับ)'),a:compareA,b:compareB})[key]||key}
chart=function(rows,keys,colors){
 const id='chart-'+(++chartSequence),w=innerWidth<760?Math.max(240,innerWidth-74):900,h=330,left=70,right=w-22,top=25,bottom=270,max=Math.max(1,...rows.flatMap(r=>keys.map(k=>Number(r[k])||0)))*1.12;
 const x=i=>left+i*(right-left)/Math.max(1,rows.length-1),y=v=>bottom-(Number(v)||0)*(bottom-top)/max;
 colors=colors.map(c=>({'#209d6d':palette.solar,'#74045f':palette.load,'#c7911b':palette.grid}[c]||c));
 const unit=keys.some(k=>k.includes('mean_kW'))||keys.includes('a')&&rows.length>6?'kW':keys.some(k=>k.includes('irradiance'))?t('Source units','หน่วยต้นฉบับ'):'kWh';
 chartData.set(id,{rows,keys,colors,left,right,x,unit});
 return `<div class="chart-wrap" data-chart="${id}"><div class="legend">${keys.map((k,i)=>`<span><i style="background:${colors[i]}"></i>${escape(chartLabel(k))}</span>`).join('')}</div><svg class="trend-chart" style="aspect-ratio:${w}/${h}" viewBox="0 0 ${w} ${h}" role="img" tabindex="0" aria-label="${t('Interactive chart. Point, tap, or use left and right arrow keys for values.','กราฟแสดงรายละเอียด ชี้เมาส์ แตะ หรือใช้ปุ่มลูกศรซ้ายขวาเพื่อดูค่า')}"><defs>${colors.map((c,i)=>`<linearGradient id="${id}-${i}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${c}" stop-opacity=".14"/><stop offset="1" stop-color="${c}" stop-opacity="0"/></linearGradient>`).join('')}</defs>${[0,.25,.5,.75,1].map(f=>`<line x1="${left}" y1="${bottom-f*(bottom-top)}" x2="${right}" y2="${bottom-f*(bottom-top)}" stroke="#294453" stroke-dasharray="3 5"/><text x="3" y="${bottom-f*(bottom-top)+5}" fill="#a8c2d3" font-size="14">${n(max*f)}</text>`).join('')}${keys.map((k,j)=>`<path d="M${left} ${bottom} ${rows.map((r,i)=>`L${x(i)} ${y(r[k])}`).join(' ')} L${right} ${bottom}Z" fill="url(#${id}-${j})"/><polyline fill="none" stroke="${colors[j]}" stroke-width="3" stroke-linejoin="round" points="${rows.map((r,i)=>`${x(i)},${y(r[k])}`).join(' ')}"/>${rows.length<3?rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r[k])}" r="5" fill="${colors[j]}"/>`).join(''):''}`).join('')}${rows.map((r,i)=>i%Math.max(1,Math.ceil(rows.length/(innerWidth<760?3:6)))===0||i===rows.length-1?`<text x="${x(i)}" y="302" text-anchor="middle" fill="#a8c2d3" font-size="14">${escape(r.label||(r.timestamp?r.timestamp.slice(11,16):r.date?.slice(8)||''))}</text>`:'').join('')}<line class="chart-cursor" x1="${left}" x2="${left}" y1="${top}" y2="${bottom}" stroke="#86edff" stroke-dasharray="4 4" visibility="hidden"/></svg><div class="chart-tip" role="status" hidden></div><p class="chart-help">${t('Hover or tap for values · Use ← → on a focused chart','ชี้เมาส์หรือแตะเพื่อดูค่า · ใช้ ← → เมื่อเลือกกราฟ')}</p></div>`;
};

function powerFlowChart(rows){
 const keys=['To Building_mean_kW','To Grid_mean_kW','From Solar_mean_kW','From Grid_mean_kW'],colors=['#53f6ce','#60e9ff','#b892f0','#ffc76b'];
 const markup=chart(rows,keys,colors),id='chart-'+chartSequence,data=chartData.get(id),w=innerWidth<760?Math.max(240,innerWidth-74):900,h=360,zero=167,range=130;
 const max=Math.max(1,...rows.map(r=>Math.max(Number(r[keys[0]]||0)+Number(r[keys[1]]||0),Number(r[keys[2]]||0)+Number(r[keys[3]]||0))))*1.1;
 const y=v=>zero-v*range/max;
 function area(low,high,color){return `<path d="${rows.map((r,i)=>`${i?'L':'M'}${data.x(i)} ${y(high(r))}`).join(' ')} ${[...rows].reverse().map((r,j)=>`L${data.x(rows.length-1-j)} ${y(low(r))}`).join(' ')}Z" fill="${color}" fill-opacity=".6" stroke="${color}" stroke-width="1.5"/>`}
 const val=(r,i)=>Number(r[keys[i]]||0);
 const plot=`<svg class="trend-chart power-chart" style="aspect-ratio:${w}/${h}" viewBox="0 0 ${w} ${h}" role="img" tabindex="0" aria-label="${t('Production above zero; consumption below zero. Point or tap for actual power values.','กำลังผลิตอยู่เหนือศูนย์ กำลังใช้ไฟอยู่ใต้ศูนย์ ชี้เมาส์หรือแตะเพื่อดูกำลังจริง')}">${[-1,-.5,0,.5,1].map(f=>`<line x1="${data.left}" x2="${data.right}" y1="${zero-f*range}" y2="${zero-f*range}" stroke="${f===0?'#59768a':'#294453'}"/><text x="3" y="${zero-f*range+5}" font-size="14" fill="#a8c2d3">${f>0?'+':f<0?'−':''}${n(Math.abs(max*f)/1000,2)}</text>`).join('')}<text x="3" y="17" font-size="14" fill="#a8c2d3">MW</text>${area(()=>0,r=>val(r,0),colors[0])}${area(r=>val(r,0),r=>val(r,0)+val(r,1),colors[1])}${area(r=>-val(r,2),()=>0,colors[2])}${area(r=>-val(r,2)-val(r,3),r=>-val(r,2),colors[3])}${rows.map((r,i)=>i%Math.max(1,Math.ceil(rows.length/(innerWidth<760?3:6)))===0||i===rows.length-1?`<text x="${data.x(i)}" y="331" text-anchor="middle" font-size="14" fill="#a8c2d3">${escape(r.timestamp.slice(11,16))}</text>`:'').join('')}<line class="chart-cursor" x1="${data.left}" x2="${data.left}" y1="25" y2="297" stroke="#86edff" stroke-dasharray="4 4" visibility="hidden"/></svg>`;
 return markup.replace(/<svg class="trend-chart"[\s\S]*?<\/svg>/,plot)+`<p class="note">${t('Above zero = production; below zero = consumption. Negative sign is a display convention.','เหนือศูนย์ = กำลังผลิต · ใต้ศูนย์ = กำลังใช้ไฟ เครื่องหมายลบเป็นรูปแบบการแสดงผล')}</p>`;
}

function bindCharts(){document.querySelectorAll('[data-chart]').forEach(wrap=>{
 const data=chartData.get(wrap.dataset.chart),svg=wrap.querySelector('svg'),tip=wrap.querySelector('.chart-tip'),cursor=wrap.querySelector('.chart-cursor');let selected=0;
 function show(i){if(!data.rows.length)return;selected=Math.max(0,Math.min(data.rows.length-1,i));const row=data.rows[selected];tip.innerHTML=`<strong>${escape(row.timestamp||row.date||row.label||'')}</strong>${data.keys.map((k,j)=>`<div><span><i style="background:${data.colors[j]}"></i>${escape(chartLabel(k))}</span><b>${n(row[k],2)} ${escape(data.unit)}</b></div>`).join('')}`;tip.hidden=false;cursor.setAttribute('x1',data.x(selected));cursor.setAttribute('x2',data.x(selected));cursor.setAttribute('visibility','visible')}
 function point(e){const matrix=svg.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());show(Math.round((p.x-data.left)/(data.right-data.left)*Math.max(1,data.rows.length-1)))}
 svg.addEventListener('pointermove',point);svg.addEventListener('pointerdown',point);svg.addEventListener('pointerleave',e=>{if(e.pointerType!=='touch'){tip.hidden=true;cursor.setAttribute('visibility','hidden')}});svg.addEventListener('focus',()=>show(selected));svg.addEventListener('blur',()=>{tip.hidden=true;cursor.setAttribute('visibility','hidden')});svg.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End','Escape'].includes(e.key)){e.preventDefault();if(e.key==='Escape'){tip.hidden=true;cursor.setAttribute('visibility','hidden')}else show(e.key==='Home'?0:e.key==='End'?data.rows.length-1:selected+(e.key==='ArrowRight'?1:-1))}});
})}
function dailyView(){let day=$('date').value||D.daily[0].date,row=D.daily.find(r=>r.date===day),hours=D.hourly.filter(r=>r.timestamp.startsWith(day));let estimated=hours.reduce((sum,r)=>sum+Number(r.Production_estimated_kWh||0),0);
 return `${row?energyCards(row,'kWh'):`<div class="status">${t('No monthly meter report for this imported date. Only hourly estimates are available.','วันที่นำเข้านี้ไม่มีรายงานพลังงานรายวัน แสดงเฉพาะค่าประมาณรายชั่วโมง')}</div>`}<section class="panel"><div class="section-heading"><h2>${t('Power flow through the day','กำลังผลิตและการใช้ไฟตลอดวัน')} · MW</h2><span>${escape(day)}</span></div>${powerFlowChart(hours)}<p class="note">${t('Each point averages four quarter-hour samples. Estimated solar energy: ','แต่ละจุดเฉลี่ยจากข้อมูล 4 จุดทุก 15 นาที พลังงานโซลาร์ประมาณ: ')}<b>${n(estimated,2)} kWh</b> · ${t('This can differ from meter totals.','อาจต่างจากยอดพลังงานในรายงาน')}</p></section><section class="panel"><h2>${t('Daily generation across the month','เทียบยอดผลิตแต่ละวันในเดือน')}</h2>${chart(D.daily,['Inverters Produced_kWh','Imported Energy_kWh'],[palette.solar,palette.grid])}<div class="actions"><button onclick="tab=6;render()">${t('Compare two days','เปรียบเทียบสองวัน')}</button></div><details><summary>${t('Show daily meter readings','ดูยอดพลังงานรายวันแบบตาราง')}</summary>${table(D.daily,[[t('Date','วันที่'),'date'],[t('Solar kWh','โซลาร์ kWh'),'Inverters Produced_kWh'],[t('Import kWh','ซื้อไฟ kWh'),'Imported Energy_kWh'],[t('Export kWh','ส่งออก kWh'),'Exported Energy_kWh']],8)}</details><details><summary>${t('Show hourly power readings','ดูรายละเอียดกำลังรายชั่วโมง')}</summary>${table(hours,[[t('Time','เวลา'),'timestamp',r=>r.timestamp.slice(11,16)],['Solar kW','Production_mean_kW'],['Load kW','Consumption_mean_kW']],8)}</details></section>`;
}
function inverterView(){inverterChoice||=D.inverters[0].inverter;const selected=D.inverters.find(r=>r.inverter===inverterChoice)||D.inverters[0],average=D.inverters.reduce((s,r)=>s+Number(r.energy_kWh),0)/D.inverters.length,ratio=(Number(selected.energy_kWh)/average-1)*100,rows=D.inverterDaily.filter(r=>r.inverter===selected.inverter),sorted=[...D.inverters].sort((a,b)=>Number(b.energy_kWh)-Number(a.energy_kWh)),max=Number(sorted[0].energy_kWh);
 return `<div class="actions"><label for="inverter-select">${t('Choose inverter','เลือกอินเวอร์เตอร์')}</label><select id="inverter-select" onchange="inverterChoice=this.value;render()">${D.inverters.map(r=>`<option value="${escape(r.inverter)}" ${r.inverter===selected.inverter?'selected':''}>${escape(r.inverter.match(/Inverter \d+/)?.[0]||r.inverter)}</option>`).join('')}</select></div><div class="cards inverter-cards">${metricCard(t('Selected inverter generation','ยอดผลิตอินเวอร์เตอร์ที่เลือก'),n(selected.energy_kWh,2),'kWh',palette.solar)}${metricCard(t('Compared with fleet average','เทียบค่าเฉลี่ยทั้ง 24 เครื่อง'),(ratio>0?'+':'')+n(ratio,2),'%',palette.load,t('Energy comparison; does not confirm faults','เทียบพลังงาน ไม่ใช้ยืนยันความขัดข้อง'))}</div><section class="panel"><h2>${escape(selected.inverter.match(/Inverter \d+/)?.[0]||selected.inverter)} · ${t('Daily generation','พลังงานผลิตรายวัน')} (kWh)</h2>${chart(rows,['energy_kWh'],[palette.solar])}</section><section class="panel"><h2>${t('All 24 inverters at a glance','เปรียบเทียบทั้ง 24 อินเวอร์เตอร์')}</h2><p class="note">${t('Highest output first. Select a row to see its daily trend.','เรียงจากผลิตมากไปน้อย เลือกเครื่องเพื่อดูกราฟรายวัน')}</p><div class="inverter-bars">${sorted.map(r=>`<button class="inverter-bar ${selected.inverter===r.inverter?'selected':''}" onclick="inverterChoice=this.dataset.inverter;render();document.getElementById('inverter-select').focus()" data-inverter="${escape(r.inverter)}"><span>${escape(r.inverter.match(/Inverter \d+/)?.[0]||r.inverter)}</span><span class="bar-track"><i style="width:${Number(r.energy_kWh)/max*100}%"></i></span><b>${n(r.energy_kWh,1)} kWh</b></button>`).join('')}</div><p class="note">${t('Lower energy may reflect system size, shade or downtime. Inverter totals are 22.262 kWh above the site report; both source totals are preserved.','ผลิตน้อยอาจเกี่ยวกับขนาด แสงเงา หรือหยุดทำงาน ยอดรวมอินเวอร์เตอร์สูงกว่ารายงานไซต์ 22.262 kWh โดยคงข้อมูลทั้งสองแหล่ง')}</p></section>`;
}
function insightView(){let best=D.daily.reduce((a,b)=>a['Inverters Produced_kWh']>b['Inverters Produced_kWh']?a:b),low=D.daily.reduce((a,b)=>a['Inverters Produced_kWh']<b['Inverters Produced_kWh']?a:b);return `<div class="cards insight-cards">${metricCard(t('Highest generation day','วันที่ผลิตสูงสุด'),n(best['Inverters Produced_kWh']/1000,2),'MWh · '+best.date,palette.solar)}${metricCard(t('Lowest generation day','วันที่ผลิตต่ำสุด'),n(low['Inverters Produced_kWh']/1000,2),'MWh · '+low.date,palette.load)}</div><section class="panel"><h2>${t('Compare production patterns','เปรียบเทียบรูปแบบการผลิต')}</h2><p>${t('See how the highest and lowest days differ hour by hour.','ดูความต่างของวันผลิตสูงสุดและต่ำสุดแบบรายชั่วโมง')}</p><button class="primary" onclick="tab=6;compareA='${best.date}';compareB='${low.date}';render()">${t('Compare these days','ดูกราฟเปรียบเทียบ')}</button></section><div class="insight-grid"><section class="panel"><h2>${t('Recorded grid export','พลังงานส่งออกที่บันทึกได้')}</h2><div class="insight-number">${n(D.summary['Exported Energy_kWh'],3)} <small>kWh</small></div><p>${t('0.2664% of solar generation','0.2664% ของพลังงานโซลาร์ที่ผลิต')}</p><p class="note">${t('Check Zero Export settings and meter logs; this alone does not establish a fault.','ควรตรวจการตั้งค่า Zero Export และบันทึกมิเตอร์ ข้อมูลนี้เพียงอย่างเดียวยังไม่ยืนยันว่าอุปกรณ์ผิดปกติ')}</p></section><section class="panel"><h2>${t('Meter data to review','วันที่ควรตรวจมิเตอร์')}</h2><div class="insight-number">18 ${t('Sep','ก.ย.')}</div><p>${t('Grid import and export were zero all day.','นำเข้าและส่งออกเป็นศูนย์ทั้งวัน')}</p><p class="note">${t('Check meter recording before concluding that solar supplied all factory consumption.','ควรตรวจการบันทึกมิเตอร์ก่อนสรุปว่าโรงงานใช้โซลาร์ทั้งหมด')}</p></section></div><details class="panel"><summary>${t('Light sensor & data limitations','เซ็นเซอร์แสงและข้อจำกัดของข้อมูล')}</summary>${chart(D.daily,['irradiance_DIRECT_source_units'],[palette.grid])}<p class="note">${t('DIRECT values are daily accumulated readings in unspecified source units. GHI is zero in all supplied records; do not use it to compute performance ratio. Meter ID 7B105205_00500 does not confirm a Janitza model. THD, PF, frequency, phase voltage/current and alarms are not supplied.','ค่า DIRECT เป็นค่าสะสมรายวัน ต้นฉบับไม่ระบุหน่วย GHI เป็นศูนย์ทุกวัน ไม่ใช้คำนวณ PR มิเตอร์ ID 7B105205_00500 ไม่ยืนยันรุ่น Janitza และไม่มีข้อมูล THD, PF, ความถี่, แรงดัน/กระแสรายเฟส หรือ alarm')}</p></details>`}
render=function(){
 chartData.clear();previousRender();document.documentElement.lang=lang;
 const current=tab===2||tab===6?1:tab===7?3:tab,index=mainSections.indexOf(current);
 $('nav').innerHTML=mainSections.map((value,i)=>`<button class="${current===value?'active':''}" aria-current="${current===value?'page':'false'}" onclick="tab=${value};page=0;render()">${icon(value)}<span>${sectionLabels[i][lang==='th'?1:0]}</span></button>`).join('')+`<div class="foot">STA PL 3MW<br>${t('September 2026 · CSV report','กันยายน 2569 · รายงาน CSV')}<br>PEA · SolarEdge · Sri Trang</div>`;
 if(index>=0)$('heading').textContent=sectionLabels[index][lang==='th'?1:0];
 $('subtitle').textContent=t('September 2026 · Historical data, not live telemetry','กันยายน 2569 · ข้อมูลรายงานย้อนหลัง');$('date').hidden=tab!==1;$('date').style.visibility=tab===1?'visible':'hidden';
 if(tab===0)$('view').innerHTML=overviewHero()+energyCards(D.summary)+`<div class="overview-grid"><section class="panel"><div class="section-heading"><h2>${t('Daily solar generation','แนวโน้มพลังงานโซลาร์รายวัน')} · kWh</h2><button onclick="tab=1;render()">${t('Explore daily data','ดูข้อมูลรายวัน')}</button></div>${chart(D.daily,['Inverters Produced_kWh'],[palette.solar])}</section>${balancePanel()}</div>`;
 if(tab===1||tab===2)$('view').innerHTML=dailyView();
 if(tab===3||tab===7)$('view').innerHTML=inverterView();
 if(tab===4)$('view').innerHTML=insightView();
 if(tab===6){$('heading').textContent=t('Compare two days','เปรียบเทียบสองวัน');$('view').insertAdjacentHTML('afterbegin',`<div><button onclick="tab=1;render()">← ${t('Back to daily energy','กลับหน้าพลังงานรายวัน')}</button></div>`)}
 if(tab===5){const panel=$('view').querySelector('.panel');const heading=panel.querySelector('h2');heading.insertAdjacentHTML('afterend',`<div class="data-summary"><strong>${D.inventory.length}</strong> ${t('source CSV files','ไฟล์ CSV ต้นฉบับ')} · <strong>${D.hourly.length}</strong> ${t('hourly records','รายการรายชั่วโมง')}<p>${t('Imports update this browser. Public data requires a dataset rebuild and publication.','การนำเข้าอัปเดตในเบราว์เซอร์นี้ ส่วนข้อมูลสาธารณะต้องคำนวณและเผยแพร่ใหม่')}</p></div>`);const tableEl=panel.querySelector('.table'),pager=panel.querySelector('.pager');if(tableEl){const details=document.createElement('details');details.innerHTML=`<summary>${t('Browse all source files','ดูรายการไฟล์ต้นฉบับทั้งหมด')}</summary>`;panel.append(details);details.append(tableEl);if(pager)details.append(pager)}}
 $('heading').closest('.title').hidden=tab===0;
 bindCharts();
};
render();
let resizeTimer,lastWidth=innerWidth;addEventListener('resize',()=>{if(innerWidth===lastWidth)return;lastWidth=innerWidth;clearTimeout(resizeTimer);resizeTimer=setTimeout(render,150)});
